PWD='/DATA/233/hli/BA_fs/Ent';PREFIX='HCP';PART='Ent';SUB_LIST='/DATA/233/hli/Data/HCP_40/sub_HCP.txt';METHOD='Sc';MPM_THRES=0.25;VOX_SIZE=2;LEFT=1;RIGHT=1;
LR='L';CL_NUM=6;MAX_CL_NUM=4;
calc_mpm_group_xmm(PWD,PREFIX,PART,SUB_LIST,MAX_CL_NUM,METHOD,MPM_THRES,VOX_SIZE,LEFT,RIGHT)